env:
  es6: true
  browser: true
  commonjs: true

extends: [
  'eslint:recommended',
  'plugin:react/recommended',
  'plugin:@typescript-eslint/eslint-recommended',
  'plugin:@typescript-eslint/recommended',
  'plugin:@typescript-eslint/recommended-requiring-type-checking',
]

parser: '@typescript-eslint/parser'

parserOptions:
  project: 'tsconfig.json'
  tsconfigRootDir: '.'

plugins: ['react', '@typescript-eslint']

settings:
  react:
    version: '16'
